# Generated by Django 4.2.5 on 2023-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_price', models.IntegerField()),
                ('item_name', models.CharField(max_length=80)),
                ('user', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
