# Generated by Django 4.2.5 on 2023-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_end_time_alter_auction_start_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
